---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Environment'
Parameters:
  ApplicationName:
    Type: String
  EnvironmentName:
    Type: String
  InstanceType:
    Description: Instance Type for Application
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
  DBInstanceSecurityGroup:
    Type: String
  DatabaseNameSSMParamName:
    Type: String
  DatabaseAddress:
    Type: String
  DatabasePort:
    Type: Number
  DatabaseUserSSMParamName:
    Type: String
  DatabasePasswordSSMParamName:
    Type: String
Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2008-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'ec2.amazonaws.com'
          Action: 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
      - !Ref Role
  Environment:
    Type: 'AWS::ElasticBeanstalk::Environment'
    Properties:
      ApplicationName: !Ref ApplicationName
      EnvironmentName: !Ref EnvironmentName
      SolutionStackName: '64bit Amazon Linux 2017.09 v2.8.3 running Docker 17.06.2-ce'
      OptionSettings:
      - Namespace: 'aws:autoscaling:launchconfiguration'
        OptionName: 'IamInstanceProfile'
        Value: !Ref InstanceProfile
      - Namespace: 'aws:autoscaling:launchconfiguration'
        OptionName: InstanceType
        Value: !Ref InstanceType
      - Namespace: 'aws:autoscaling:launchconfiguration'
        OptionName: EC2KeyName
        Value: !ImportValue SSHKey
      - Namespace: 'aws:autoscaling:launchconfiguration'
        OptionName: SecurityGroups
        Value: !Ref DBInstanceSecurityGroup
      - Namespace:  aws:elb:loadbalancer
        OptionName:  SSLCertificateId
        Value:  !ImportValue SSLArn
      - Namespace: 'aws:elasticbeanstalk:application:environment'
        OptionName: DB_NAME
        Value: !Ref DatabaseNameSSMParamName
      - Namespace: 'aws:elasticbeanstalk:application:environment'
        OptionName: DB_ADDRESS
        Value: !Ref DatabaseAddress
      - Namespace: 'aws:elasticbeanstalk:application:environment'
        OptionName: DB_PORT
        Value: !Ref DatabasePort
      - Namespace: 'aws:elasticbeanstalk:application:environment'
        OptionName: DB_PASS
        Value: !Ref DatabasePasswordSSMParamName
      - Namespace: 'aws:elasticbeanstalk:application:environment'
        OptionName: DB_USER
        Value: !Ref DatabaseUserSSMParamName
Outputs:
  EnvironmentName:
    Value: !Ref Environment
  EndpointURL:
    Value: !Sub '${Environment.EndpointURL}'
